# Use the official PostgreSQL image
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=Events

# Expose PostgreSQL port
EXPOSE 5432

# Default command to run PostgreSQL
CMD ["postgres"]
